version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
    target-branch: "dev"
    labels:
      - "gomod dependencies"
    reviewers:
      - "neelvirdy"
