# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

builds:
  - main: .
    id: "estuary"
    binary: estuary
    goos:
      - linux
      - darwin
    goarch:
      - 386
      - amd64
      - arm64
    hooks:
      pre:
       - cmd: git submodule update --init --recursive && cd extern/filecoin-ffi/ && git checkout -q 
       - cmd: make -C extern/filecoin-ffi/ .install-filcrypto
      post:
       - cmd: git submodule deinit . 

  - main: ./cmd/estuary-shuttle
    id: "estuary-shuttle"
    binary: estuary-shuttle
    goos:
      - linux
      - darwin

  - main: ./cmd/barge
    id: "barge"
    binary: barge
    goos:
      - linux
      - darwin

  - main: ./cmd/benchest
    id: "benchest"
    binary: benchest
    goos:
      - linux
      - darwin
  
  - main: ./cmd/bsget
    id: "bsget"
    binary: bsget
    goos:
      - linux
      - darwin

  - main: ./cmd/shuttle-proxy
    id: "shuttle-proxy"
    binary: shuttle-proxy
    goos:
      - linux
      - darwin

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
