// Package docs GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate_swagger = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://estuary.tech",
        "contact": {
            "name": "API Support",
            "url": "https://docs.estuary.tech/feedback"
        },
        "license": {
            "name": "Apache 2.0 Apache-2.0 OR MIT",
            "url": "https://github.com/application-research/estuary/blob/master/LICENSE.md"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/users": {
            "get": {
                "description": "This endpoint is used to get all users.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin",
                    "Users"
                ],
                "summary": "Get all users",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/main.adminUserResponse"
                            }
                        }
                    }
                }
            }
        },
        "/collections/add-content": {
            "post": {
                "description": "When a collection is created, users with valid API keys can add contents to the collection. This endpoint can be used to add contents to a collection.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "collections"
                ],
                "summary": "Add contents to a collection",
                "parameters": [
                    {
                        "description": "Contents to add to collection",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.addContentToCollectionParams"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/collections/content/:collection-id": {
            "get": {
                "description": "This endpoint is used to get contents in a collection. When a collection is created, this collection object is retrievable along with its content via this endpoint.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "collections"
                ],
                "summary": "Get contents in a collection",
                "parameters": [
                    {
                        "type": "string",
                        "description": "coluuid",
                        "name": "coluuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/collections/create": {
            "post": {
                "description": "This endpoint is used to create a new collection. A collection is a representaion of a group of objects added on the estuary. This endpoint can be used to create a new collection.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "collections"
                ],
                "summary": "Create a new collection",
                "parameters": [
                    {
                        "description": "Collection name and description",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.createCollectionBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.Collection"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/util.HttpError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/util.HttpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/util.HttpError"
                        }
                    }
                }
            }
        },
        "/collections/fs/add": {
            "post": {
                "description": "This endpoint adds a file to a collection",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "collections"
                ],
                "summary": "Add a file to a collection",
                "responses": {}
            }
        },
        "/collections/fs/list": {
            "get": {
                "description": "This endpoint creates a new collection",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "collections"
                ],
                "summary": "Create a new collection",
                "responses": {}
            }
        },
        "/collections/list": {
            "get": {
                "description": "This endpoint is used to list all collections. Whenever a user logs on estuary, it will list all collections that the user has access to. This endpoint provides a way to list all collections to the user.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "collections"
                ],
                "summary": "List all collections",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/main.Collection"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/util.HttpError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/util.HttpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/util.HttpError"
                        }
                    }
                }
            }
        },
        "/content/add": {
            "post": {
                "description": "This endpoint is used to upload new content.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "content"
                ],
                "summary": "Add new content",
                "responses": {}
            }
        },
        "/content/add-car": {
            "post": {
                "description": "This endpoint is used to add a car object to the network. The object can be a file or a directory.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "content"
                ],
                "summary": "Add Car object",
                "responses": {}
            }
        },
        "/content/add-ipfs": {
            "post": {
                "description": "This endpoint is used to add an IPFS object to the network. The object can be a file or a directory.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "content"
                ],
                "summary": "Add IPFS object",
                "responses": {}
            }
        },
        "/content/aggregated/:content": {
            "get": {
                "description": "This endpoint returns aggregated content stats",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "content"
                ],
                "summary": "Get aggregated content stats",
                "responses": {}
            }
        },
        "/content/all-deals": {
            "get": {
                "description": "This endpoint is used to get all deals for a user",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "content"
                ],
                "summary": "Get all deals for a user",
                "responses": {}
            }
        },
        "/content/bw-usage/:content": {
            "get": {
                "description": "This endpoint returns content bandwidth",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "content"
                ],
                "summary": "Get content bandwidth",
                "responses": {}
            }
        },
        "/content/create": {
            "post": {
                "description": "This endpoint adds a new content",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "content"
                ],
                "summary": "Add a new content",
                "responses": {}
            }
        },
        "/content/deals": {
            "get": {
                "description": "This endpoint lists all content with deals",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "content"
                ],
                "summary": "Content with deals",
                "responses": {}
            }
        },
        "/content/ensure-replication/:datacid": {
            "get": {
                "description": "This endpoint ensures that the content is replicated to the specified number of providers",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "content"
                ],
                "summary": "Ensure Replication",
                "responses": {}
            }
        },
        "/content/failures/:content": {
            "get": {
                "description": "This endpoint returns all failures for a content",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "content"
                ],
                "summary": "List all failures for a content",
                "responses": {}
            }
        },
        "/content/importdeal": {
            "post": {
                "description": "This endpoint imports a deal into the shuttle.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "content"
                ],
                "summary": "Import a deal",
                "responses": {}
            }
        },
        "/content/list": {
            "get": {
                "description": "This endpoint lists all content",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "content"
                ],
                "summary": "List all pinned content",
                "responses": {}
            }
        },
        "/content/read/:cont": {
            "get": {
                "description": "This endpoint reads content from the blockstore",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "content"
                ],
                "summary": "Read content",
                "responses": {}
            }
        },
        "/content/staging-zones": {
            "get": {
                "description": "This endpoint is used to get staging zone for user",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "content"
                ],
                "summary": "Get staging zone for user",
                "responses": {}
            }
        },
        "/content/stats": {
            "get": {
                "description": "This endpoint is used to get content statistics. Every content stored in the network (estuary) is tracked by a unique ID which can be used to get information about the content. This endpoint will allow the consumer to get the collected stats of a conten",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "content"
                ],
                "summary": "Get content statistics",
                "responses": {}
            }
        },
        "/content/status/:id": {
            "get": {
                "description": "This endpoint returns the status of a content",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "content"
                ],
                "summary": "Content Status",
                "responses": {}
            }
        },
        "/deal/estimate": {
            "get": {
                "description": "This endpoint estimates the cost of a deal",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "deals"
                ],
                "summary": "Estimate the cost of a deal",
                "responses": {}
            }
        },
        "/deal/info/:dealid": {
            "get": {
                "description": "This endpoint returns the deal info for a deal",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "deals"
                ],
                "summary": "Get Deal Info",
                "responses": {}
            }
        },
        "/deal/make/:miner": {
            "post": {
                "description": "This endpoint makes a deal for a given content and miner",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "deals"
                ],
                "summary": "Make Deal",
                "responses": {}
            }
        },
        "/deal/proposal/:propcid": {
            "get": {
                "description": "This endpoint returns the proposal for a deal",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "deals"
                ],
                "summary": "Get Proposal",
                "responses": {}
            }
        },
        "/deal/query/:miner": {
            "get": {
                "description": "This endpoint returns the ask for a given CID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "deals"
                ],
                "summary": "Query Ask",
                "responses": {}
            }
        },
        "/deal/status-by-proposal/:propcid": {
            "get": {
                "description": "Get Deal Status by PropCid",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "deals"
                ],
                "summary": "Get Deal Status by PropCid",
                "responses": {}
            }
        },
        "/deal/status/:deal": {
            "get": {
                "description": "This endpoint returns the status of a deal",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "deals"
                ],
                "summary": "Get Deal Status",
                "responses": {}
            }
        },
        "/deal/status/:miner/:propcid": {
            "get": {
                "description": "This endpoint returns the status of a deal",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "deals"
                ],
                "summary": "Deal Status",
                "responses": {}
            }
        },
        "/deal/transfer/in-progress": {
            "get": {
                "description": "This endpoint returns the in-progress transfers",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "deals"
                ],
                "summary": "Transfer In Progress",
                "responses": {}
            }
        },
        "/deal/transfer/status": {
            "post": {
                "description": "This endpoint returns the status of a transfer",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "deals"
                ],
                "summary": "Transfer Status",
                "responses": {}
            }
        },
        "/pinning/pins": {
            "get": {
                "description": "This endpoint lists all pinned objects",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pinning"
                ],
                "summary": "List all pinned objects",
                "responses": {
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/util.HttpError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/util.HttpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/util.HttpError"
                        }
                    }
                }
            },
            "post": {
                "description": "This endpoint adds a pin to the IPFS daemon.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pinning"
                ],
                "summary": "Add and pin object",
                "parameters": [
                    {
                        "type": "string",
                        "description": "cid",
                        "name": "cid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/pinning/pins/:id": {
            "get": {
                "description": "This endpoint returns a pinned object.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pinning"
                ],
                "summary": "Get a pinned objects",
                "parameters": [
                    {
                        "type": "string",
                        "description": "cid",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            },
            "post": {
                "description": "This endpoint replaces a pinned object.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pinning"
                ],
                "summary": "Replace a pinned object",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            },
            "delete": {
                "description": "This endpoint deletes a pinned object.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pinning"
                ],
                "summary": "Delete a pinned object",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/public/by-cid/:cid": {
            "get": {
                "description": "This endpoint returns the content associated with a CID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "public"
                ],
                "summary": "Get Content by Cid",
                "responses": {}
            }
        },
        "/public/deal/failures": {
            "get": {
                "description": "This endpoint returns a list of storage failures",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "public",
                    "deals"
                ],
                "summary": "Get storage failures",
                "responses": {}
            }
        },
        "/public/info": {
            "get": {
                "description": "This endpoint returns information about the node",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "public",
                    "deals"
                ],
                "summary": "Get public node info",
                "responses": {}
            }
        },
        "/public/metrics/deals-on-chain": {
            "get": {
                "description": "This endpoint is used to get deal metrics",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "public",
                    "metrics"
                ],
                "summary": "Get deal metrics",
                "responses": {}
            }
        },
        "/public/miners": {
            "get": {
                "description": "This endpoint returns all miners",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "public",
                    "net"
                ],
                "summary": "Get all miners",
                "responses": {}
            }
        },
        "/public/miners/deals/:miner": {
            "get": {
                "description": "This endpoint returns all miners deals",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "public",
                    "miner"
                ],
                "summary": "Get all miners deals",
                "responses": {}
            }
        },
        "/public/miners/failures/:miners": {
            "get": {
                "description": "This endpoint returns all miners",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "public",
                    "net"
                ],
                "summary": "Get all miners",
                "responses": {}
            }
        },
        "/public/miners/stats/:miner": {
            "get": {
                "description": "This endpoint returns miner stats",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "public",
                    "miner"
                ],
                "summary": "Get miner stats",
                "responses": {}
            }
        },
        "/public/net/addrs": {
            "get": {
                "description": "This endpoint is used to get net addrs",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "public",
                    "net"
                ],
                "summary": "Net Addrs",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/public/net/peers": {
            "get": {
                "description": "This endpoint is used to get net peers",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "public",
                    "net"
                ],
                "summary": "Net Peers",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/public/stats": {
            "get": {
                "description": "This endpoint is used to get public stats.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "public"
                ],
                "summary": "Public stats",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.publicStatsResponse"
                        }
                    }
                }
            }
        },
        "/user/api-keys": {
            "get": {
                "description": "This endpoint is used to get API keys for a user. In estuary, each user can be given multiple API keys (tokens). This endpoint can be used to retrieve all available API keys for a given user.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Get API keys for a user",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/main.getApiKeysResp"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/util.HttpError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/util.HttpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/util.HttpError"
                        }
                    }
                }
            },
            "post": {
                "description": "This endpoint is used to create API keys for a user. In estuary, each user is given an API key to access all features.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Create API keys for a user",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.getApiKeysResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/util.HttpError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/util.HttpError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/util.HttpError"
                        }
                    }
                }
            }
        },
        "/user/api-keys/:key": {
            "delete": {
                "description": "This endpoint is used to revoke a user API key. In estuary, every user is assigned with an API key, this API key is generated and issued for each user and is primarily use to access all estuary features. This endpoint can be used to revoke the API key thats assigned to the user.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Revoke a User API Key.",
                "responses": {}
            }
        },
        "/user/export": {
            "get": {
                "description": "This endpoint is used to get API keys for a user.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Export user data",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/user/stats": {
            "get": {
                "description": "This endpoint is used to create API keys for a user.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Create API keys for a user",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.userStatsResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "main.Collection": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "userId": {
                    "type": "integer"
                },
                "uuid": {
                    "type": "string"
                }
            }
        },
        "main.addContentToCollectionParams": {
            "type": "object",
            "properties": {
                "cids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "collection": {
                    "type": "string"
                },
                "contents": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "main.adminUserResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "numFiles": {
                    "type": "integer"
                },
                "spaceUsed": {
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "main.createCollectionBody": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "main.getApiKeysResp": {
            "type": "object",
            "properties": {
                "expiry": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "main.publicStatsResponse": {
            "type": "object",
            "properties": {
                "dealsOnChain": {
                    "type": "integer"
                },
                "totalFiles": {
                    "type": "integer"
                },
                "totalStorage": {
                    "type": "integer"
                }
            }
        },
        "main.userStatsResponse": {
            "type": "object",
            "properties": {
                "numPins": {
                    "type": "integer"
                },
                "totalSize": {
                    "type": "integer"
                }
            }
        },
        "util.HttpError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "details": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.0.0",
	Host:             "api.estuary.tech",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Estuary API",
	Description:      "This is the API for the Estuary application.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate_swagger,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
