name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        default: true

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install hwloc libhwloc-dev jq ocl-icd-opencl-dev jq

    - name: Build
      run: make clean all

    - name: Run linters
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.29

    - name: Setup
      run: echo "ESTUARY_TOKEN=$(./estuary setup | grep Token | cut -d ' ' -f 3)" >> $GITHUB_ENV

    - name: Test
      run: go test -v -covermode=count ./...
      env:
        ESTUARY_TOKEN: $ESTUARY_TOKEN
    
    - name: Calculate coverage
      run: go test -v -covermode=count -coverprofile=coverage.out
    
    - name: Convert coverage.out to coverage.lcov
      uses: jandelgado/gcov2lcov-action@v1.0.6

    - name: Coveralls
      uses: coverallsapp/github-action@v1.1.2
      with:
        github-token: ${{ secrets.github_token }}
        path-to-lcov: coverage.lcov
