name: Swagger docs

on:
  push:
  pull_request:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Build
      run: make generate-swagger 

    - name: Add docs
      uses: maxgfr/github-commit-push-file@main
      with:
        commit_name: 'docs: update swagger docs'
