name: Swagger docs

on:
  push:
  pull_request:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Build
      run: make generate-swagger 

    - name: Add docs
      uses: actions-go/push@master
      with:
        commit-message: 'docs: update swagger docs'
